### ISSUE TITLE
Does this have a re-authorize access key mechanism? Also, how are the API requests being handled?

### ISSUE THREAD

**Issue by giveandtake** [djpate/OAuthProviderExample#1]
How would an API call after you receive the access token work?

What happens if the access token expires?

**Comment by djpate** [comment]
You can find the client call here
https://github.com/djpate/OAuthProviderExample/blob/master/client/apicall.php
And the provider handling here
https://github.com/djpate/OAuthProviderExample/blob/master/oauth/index.php#L22

This provider doesnt have a re-authorize mechanism since access token doesn't expire.
The only way to actually revoke an access token is to delete it from the DB.

The client would then receive a OAUTH_TOKEN_REJECTED

**Comment by giveandtake** [comment]
okay what about making ajax calls using the oauth access token?

**Comment by djpate** [comment]
I dont see what you mean ? If you want to use ajax just load the apicall.php then parse it using js. If you actually want to make the call using only js you'll need to find a oauth client for js but since you dont want to expose your credentials I'm not sure that it exists...

**Comment by giveandtake** [comment]
good to know thanks
